calapp/urls.py
from django.urls import path
from . import views

app_name = 'calapp'

urlpatterns = [
    # path('', views.MonthCalendar.as_view(), name='month'),
    # path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    # path('week/', views.WeekCalendar.as_view(), name='week'),
    # path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    # path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    # path(
    #     'week_with_schedule/<int:year>/<int:month>/<int:day>/',
    #     views.WeekWithScheduleCalendar.as_view(),
    #     name='week_with_schedule'
    # ),
    # path(
    #     'month_with_schedule/',
    #     views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    # ),
    # path(
    #     'month_with_schedule/<int:year>/<int:month>/',
    #     views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    # ),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),
    path('schedule/change/<int:pk>/', views.ScheduleChange.as_view(), name='schedule_change'),
    path('schedule/delete/<int:pk>/', views.ScheduleDelete.as_view(), name='schedule_delete'),
]

dailymemo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('create_account', views.SignUpView.as_view(), name='create_account'),
    path('',include('calapp.urls')),
]

templates/includes/month.html
<a href="{% url 'calapp:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'calapp:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
        {% for w in week_names %}
            <th>{{ w }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
            {% for day in week %}
                {% if now == day %}
                    <td class="table-success">
                {% else %}
                    <td>
                {% endif %}

                <a href="{% url 'calapp:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/includes/week.html
<a href="{% url 'calapp:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'calapp:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
    <tbody>
    <tr>
        {% for day in week_days %}
            {% if now == day %}
                <td class="table-success">
                    {% else %}
                <td>
            {% endif %}
        {% if week_first.month != day.month %}
            {{ day | date:"m/d" }}
        {% else %}
            {{ day.day }}
        {% endif %}
        </td>
        {% endfor %}
    </tr>
    <tr>
        {% for schedules in week_day_schedules.values %}
            <td>
                {% for s in schedules %}
                    {{ s.start_time }} - {{ s.end_time }}<br>
                    <p><a href="{% url 'calapp:schedule_change' s.pk %}">{{ s.summary }}</a></p><br>
                    {{ s.description | linebreaks }}
                {% endfor %}
            </td>
        {% endfor %}
    </tr>
    </tbody>
</table>