calapp/urls.py
from django.urls import path
from . import views

app_name = 'calapp'

urlpatterns = [
    # path('', views.MonthCalendar.as_view(), name='month'),
    # path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    # path('week/', views.WeekCalendar.as_view(), name='week'),
    # path('week/<int:year>/<int:month>/<int:day>/', views.WeekCalendar.as_view(), name='week'),
    # path('week_with_schedule/', views.WeekWithScheduleCalendar.as_view(), name='week_with_schedule'),
    # path(
    #     'week_with_schedule/<int:year>/<int:month>/<int:day>/',
    #     views.WeekWithScheduleCalendar.as_view(),
    #     name='week_with_schedule'
    # ),
    # path(
    #     'month_with_schedule/',
    #     views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    # ),
    # path(
    #     'month_with_schedule/<int:year>/<int:month>/',
    #     views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    # ),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),
    path('schedule/change/<int:pk>/', views.ScheduleChange.as_view(), name='schedule_change'),
    path('schedule/delete/<int:pk>/', views.ScheduleDelete.as_view(), name='schedule_delete'),
]

dailymemo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('create_account', views.SignUpView.as_view(), name='create_account'),
    path('',include('calapp.urls')),
]

calapp/models.py
import datetime
from django.db import models
from django.utils import timezone


class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://getbootstrap.com/docs/4.1/examples/sign-in/signin.css" rel="stylesheet">
  
<title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <div class="container">
    <div class="content">
      {% block content %}
      {% endblock %}        
    </div>  
  </div>
  </main>
</body>
</html>

templates/base_cal.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
    <nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-primary box-shadow">
        <a class="navbar-brand" >
            ChukaSoba
        </a>
        <div class="collapse navbar-collapse justify-content-end"></div>
        <ul class="navbar-nav">
        {% if user.id is None %}
        <!-- ログインしていなかったらこっち -->
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">新規登録</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">ログイン</a></li>
        {% else %}
        <!-- ログインしていたらこっち -->
        <li class ="nav-item"><a class="nav-link">ユーザ名：{{ user.get_username }}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">ログアウト</a></li>
        {% endif %}
        </ul>
        </div>
    </nav>
</head>
<body>
<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

templates/create.html
{% extends "base.html" %}
{% block title %}Signup{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7 col-sm-9">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Sign up</h3>
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger alert-text" role="alert">
                                {% for error in form.non_field_errors %}
                                    <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <form method="POST" action="{% url 'create_account' %}" class="auth-form" novalidate>
                            {% csrf_token %}
                            {% for field in form %}
                            <div>
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.errors %}
                                    <div class="login-error-text">
                                        {{ field.errors }}
                                    </div>
                                {% else %}
                                    <div class="login-text-div"></div>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <button type="submit" class="form-control btn-primary auth-button">登録</button>
                        </form>
                    </div>
                    <div class="card-footer text-muted text-center">
                        Already have an account? <a href="{% url 'login' %}">Log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/month.html
{% extends 'base_cal.html' %}

{% block content %}
    <a href="{% url 'calapp:month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'calapp:month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/month_with_schedule.html
{% extends 'base_cal.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            {# white-space: nowrap; #}
        }

    </style>
    <a href="{% url 'calapp:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'calapp:month_with_schedule' month_next.year month_next.month %}">次月</a>
    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                        <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/mycalendar.html
{% extends 'base_cal.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            {% include 'includes/month.html' %}
            <hr>
            <form action="" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">送信</button>
            </form>
        </div>
        <div class="col-md-9">
            {% include 'includes/week.html' %}
        </div>
    </div>
{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/schedule_form.html
{% extends 'base_cal.html' %}

{% block content %}
    <a href="{{request.META.HTTP_REFERER}}">戻る</a>
    <hr>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">送信</button>
    </form>
    <hr>
    <form action="{% url 'calapp:schedule_delete' schedule.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">削除</button>
    </form>

{% endblock %}


{% block extrajs %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <script>
        $(function () {
            // timedropper
            $("#id_start_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
            $("#id_end_time").timeDropper({
                format: "H:mm",
                setCurrentTime: false,
            });
        });
    </script>
{% endblock %}

templates/week.html
{% extends 'base_cal.html' %}
{% block content %}

    <a href="{% url 'calapp:week' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'calapp:week' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day in week_days %}
                {% if now == day %}
                    <td class="table-success">
                        {% else %}
                    <td>
                {% endif %}
            {% if week_first.month != day.month %}
                {{ day | date:"m/d" }}
            {% else %}
                {{ day.day }}
            {% endif %}
            </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/week_with_schedule.html
{% extends 'base_cal.html' %}
{% block content %}

    <a href="{% url 'calapp:week_with_schedule' week_previous.year week_previous.month  week_previous.day %}">前週</a>
    {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
    <a href="{% url 'calapp:week_with_schedule' week_next.year week_next.month  week_next.day %}">次週</a>

    <table class="table table-bordered">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for day, schedules in week_day_schedules.items %}
                <td>
                    <!-- 日付 -->
                    {% if week_first.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}
                    <br>

                    <!-- その日のスケジュール -->
                    {% for s in schedules %}
                        {{ s.start_time }} - {{ s.end_time }}<br>
                        {{ s.summary }}<br>
                        {{ s.description | linebreaks }}
                    {% endfor %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endblock %}